version: "3.7"

services:
    nginx:
        build: ./docker/nginx
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/www/sparrow
        ports:
            - "80:80"
            - "37062:37062"
            - "37063:37063"
    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./:/www/sparrow
            - ./docker/php-fpm/supervisor_conf.d:/etc/supervisor/conf.d
        working_dir: /www/sparrow
        entrypoint: sh -c "supervisord & docker-php-entrypoint php-fpm"
    mysql:
        build: ./docker/mysql
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: xxxx
    redis:
        build: ./docker/redis
        volumes:
            - ./docker/redis/data:/data
    rabbitmq:
        build: ./docker/rabbitmq
        volumes:
            - ./docker/rabbitmq/data:/var/lib/rabbitmq
        ports:
            - "15672:15672"
