version: "3.7"

services:
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - $WWW:/project
        ports:
            - "80:80"
    php-fpm:
        build: ./php-fpm
        volumes:
            - $WWW:/www
        working_dir: /www
    mysql:
        build: ./mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: xxxx
    redis:
        build: ./redis
        volumes:
            - ./redis/data:/data
    rabbitmq:
        build: ./rabbitmq
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq
        ports:
            - "15672:15672"
